spring:
  application:
    name: trade-websocket
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: mongodb://localhost:27017/otc
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 1
    timeout: 60s
    database: 0
  datasource:
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5

server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8